import type { Course } from './table-example.types';

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title: 'React Fundamentals',
    category: 'programming',
    instructor: 'Alice Johnson',
    status: 'published',
    enrollments: 1240,
    rating: 4.8,
    isFree: false,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'TypeScript Deep Dive',
    category: 'programming',
    instructor: 'Bob Williams',
    status: 'published',
    enrollments: 870,
    rating: 4.6,
    isFree: false,
    createdAt: '2024-02-03',
  },
  {
    id: '3',
    title: 'UI/UX Design Principles',
    category: 'design',
    instructor: 'Carol Martinez',
    status: 'published',
    enrollments: 590,
    rating: 4.5,
    isFree: true,
    createdAt: '2024-02-20',
  },
  {
    id: '4',
    title: 'Next.js Advanced Patterns',
    category: 'programming',
    instructor: 'Alice Johnson',
    status: 'draft',
    enrollments: 0,
    rating: 0,
    isFree: false,
    createdAt: '2024-03-01',
  },
  {
    id: '5',
    title: 'Figma for Developers',
    category: 'design',
    instructor: 'Carol Martinez',
    status: 'published',
    enrollments: 430,
    rating: 4.3,
    isFree: true,
    createdAt: '2024-03-10',
  },
  {
    id: '6',
    title: 'Digital Marketing 101',
    category: 'marketing',
    instructor: 'David Lee',
    status: 'published',
    enrollments: 750,
    rating: 4.1,
    isFree: false,
    createdAt: '2024-03-18',
  },
  {
    id: '7',
    title: 'Business Strategy',
    category: 'business',
    instructor: 'Eve Thompson',
    status: 'archived',
    enrollments: 310,
    rating: 3.9,
    isFree: false,
    createdAt: '2023-11-05',
  },
  {
    id: '8',
    title:
      'Python for Data Science Python for Data Science Python for Data Science',
    category: 'science',
    instructor: 'Frank Garcia',
    status: 'published',
    enrollments: 2100,
    rating: 4.9,
    isFree: false,
    createdAt: '2024-01-28',
  },
  {
    id: '9',
    title: 'Node.js REST APIs',
    category: 'programming',
    instructor: 'Bob Williams',
    status: 'published',
    enrollments: 660,
    rating: 4.4,
    isFree: false,
    createdAt: '2024-04-05',
  },
  {
    id: '10',
    title: 'Social Media Strategy',
    category: 'marketing',
    instructor: 'David Lee',
    status: 'draft',
    enrollments: 0,
    rating: 0,
    isFree: false,
    createdAt: '2024-04-12',
  },
  {
    id: '11',
    title: 'Intro to Machine Learning',
    category: 'science',
    instructor: 'Frank Garcia',
    status: 'published',
    enrollments: 1580,
    rating: 4.7,
    isFree: false,
    createdAt: '2024-02-14',
  },
  {
    id: '12',
    title: 'Startup Fundamentals',
    category: 'business',
    instructor: 'Eve Thompson',
    status: 'published',
    enrollments: 420,
    rating: 4.2,
    isFree: true,
    createdAt: '2024-03-25',
  },
  {
    id: '13',
    title: 'CSS Grid & Flexbox',
    category: 'design',
    instructor: 'Carol Martinez',
    status: 'archived',
    enrollments: 185,
    rating: 3.8,
    isFree: true,
    createdAt: '2023-12-01',
  },
  {
    id: '14',
    title: 'Vue.js Complete Guide',
    category: 'programming',
    instructor: 'Alice Johnson',
    status: 'published',
    enrollments: 510,
    rating: 4.3,
    isFree: false,
    createdAt: '2024-04-20',
  },
  {
    id: '15',
    title: 'SEO Mastery',
    category: 'marketing',
    instructor: 'David Lee',
    status: 'published',
    enrollments: 390,
    rating: 4.0,
    isFree: false,
    createdAt: '2024-04-28',
  },
  {
    id: '16',
    title: 'Deep Learning with PyTorch',
    category: 'science',
    instructor: 'Frank Garcia',
    status: 'draft',
    enrollments: 0,
    rating: 0,
    isFree: false,
    createdAt: '2024-05-01',
  },
  {
    id: '17',
    title: 'Product Management Basics',
    category: 'business',
    instructor: 'Eve Thompson',
    status: 'published',
    enrollments: 640,
    rating: 4.5,
    isFree: false,
    createdAt: '2024-03-08',
  },
  {
    id: '18',
    title: 'GraphQL with Apollo',
    category: 'programming',
    instructor: 'Bob Williams',
    status: 'published',
    enrollments: 295,
    rating: 4.2,
    isFree: false,
    createdAt: '2024-05-10',
  },
  {
    id: '19',
    title: 'Motion Design with After Effects',
    category: 'design',
    instructor: 'Carol Martinez',
    status: 'published',
    enrollments: 220,
    rating: 4.1,
    isFree: false,
    createdAt: '2024-04-15',
  },
  {
    id: '20',
    title: 'E-Commerce Analytics',
    category: 'marketing',
    instructor: 'David Lee',
    status: 'archived',
    enrollments: 160,
    rating: 3.7,
    isFree: false,
    createdAt: '2023-10-20',
  },
];
